---
- hosts: all
  become: true
  pre_tasks:
    - name: Refresh APT package index on Ubuntu
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Refresh YUM package index on CentOS
      ansible.builtin.yum:
        update_cache: yes
      when: ansible_distribution == "CentOS"

- hosts: ubuntu_server
  become: true
  roles:
    - role: installing_ubuntu_docker

- hosts: centos_server
  become: true
  roles:
    - role: installing_centos_docker